# -*- coding: utf-8 -*-
"""Assingement 12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BV2WqTR63Ke5ObqCdTqAMmE8fp5HvA5i
"""

#1.
# A Decision Tree is a supervised machine learning algorithm used for both classification and regression tasks. It works like a flowchart where:

# Each internal node represents a feature (attribute).
# Each branch represents a decision rule.
# Each leaf node represents the final class label.

# # 2.
# Difference Between Decision Tree and Random Forest
# Feature	Decision Tree	Random Forest
# Model Type	Single Tree	Multiple Trees
# Accuracy	Lower	Higher
# Overfitting	High	Less
# Training Speed	Faster	Slower

# # 3.
# Naive Bayes Classifier

# Naive Bayes is a probabilistic classification algorithm based on Bayes Theorem.

# It assumes that all features are independent of each other.

# # 4
# Classify an Email Containing "Offer"

# Dataset:

# Contains Offer	Email Type
# Yes	              Spam
# Yes              	Spam
# No            	Not Spam
# No	            Not Spam
# Yes	             Spam
# No	           Not Spam


# Spam prior=3/6, NotSpam=3/6. P(Offer|Spam)=3/3=1, P(Offer|NotSpam)=0/3=0. Therefore classify as **Spam**.

# 5
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier,plot_tree
from sklearn.metrics import confusion_matrix,accuracy_score
import matplotlib.pyplot as plt
iris=load_iris()
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.2,random_state=42)
model=DecisionTreeClassifier(random_state=42)
model.fit(X_train,y_train)
pred=model.predict(X_test)
print("Accuracy:",accuracy_score(y_test,pred))
print(confusion_matrix(y_test,pred))
plt.figure(figsize=(12,8))
plot_tree(model,filled=True,feature_names=iris.feature_names,class_names=iris.target_names)
plt.show()

# 6.
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,accuracy_score
url='https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'
df=pd.read_csv(url)
df=df[['Pclass','Sex','Age','Fare','Survived']].dropna()
df['Sex']=df['Sex'].map({'male':0,'female':1})
X=df.drop('Survived',axis=1)
y=df['Survived']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
rf=RandomForestClassifier(random_state=42)
rf.fit(X_train,y_train)
pred=rf.predict(X_test)
print('Accuracy:',accuracy_score(y_test,pred))
print(classification_report(y_test,pred))